version: "3"
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data-mongo:/data/mongo

  postgres:
    image: postgres:14.4
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ddd_inventory
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data-postgres:/data/postgres

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - data-rabbitmq:/var/lib/rabbitmq

  command-app:
    image: julian362/command-app:v4
    container_name: command-app
    ports:
      - 3000:3000
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: password
      MONGO_URL: mongodb://root:password@mongo:27017/ddd_inventory?authSource=admin
      MONGO_NAME: ddd_inventory
      RABBITMQ_HOST: amqp://root:password@rabbitmq:5672
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - inventory-app:/command/app

  querie-app:
    image: julian362/querie-app:v4
    container_name: querie-app
    ports:
      - 3001:3001
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: ddd_inventory
      RABBITMQ_HOST: amqp://root:password@rabbitmq:5672
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq
      - command-app
    volumes:
      - inventory-app:/querie/app

  proxy-app:
    image: julian362/proxy-app:v4
    container_name: proxy-app
    ports:
      - 3002:3002
      - 81:81
    environment:
      RABBITMQ_HOST: amqp://root:password@rabbitmq:5672
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - command-app
    volumes:
      - inventory-app:/proxy/app

  front-app:
    image: "julian362/inventory-front:latest"
    container_name: front-app
    restart: always
    ports:
      - 4200:4200
    depends_on:
      - command-app
      - querie-app
      - proxy-app
    volumes:
      - front-app:/usr/share/nginx/html

volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  data-rabbitmq:
    name: data-rabbitmq
    driver: local
  inventory-app:
    name: inventory-app
    driver: local
  front-app:
    name: front-app
    driver: local